# Generated by Django 3.2.15 on 2022-09-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите тэг", related_name="recipe", to="recipes.Tag"
            ),
        ),
    ]
