# Generated by Django 3.2.15 on 2022-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите тэг",
                related_name="recipe",
                to="recipes.Tag",
                verbose_name="Тэг блюда",
            ),
        ),
    ]
