# Generated by Django 3.2.15 on 2022-09-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='recipe',
            new_name='_recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Выберете ингридиенты', related_name='recipe', to='recipes.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='ingredients',
            field=models.ManyToManyField(help_text='Выберете ингридиенты', related_name='recipe_ingredients', to='recipes.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
    ]
