# Generated by Django 3.2.15 on 2022-09-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_auto_20220920_1755"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredients",
            name="ingredients",
        ),
    ]
