# Generated by Django 3.2.15 on 2022-09-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipeingredients_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='_ingredients',
            new_name='ingredients',
        ),
    ]
