# Generated by Django 3.2.15 on 2022-10-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipetags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите время приготовления блюда в минутах",
                verbose_name="Время приготовления блюда",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(
                help_text="Введите текстовое описание",
                verbose_name="Текстовое описание",
            ),
        ),
    ]
