# Generated by Django 3.2.15 on 2022-09-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_last_name"),
    ]

    operations = []
