# Generated by Django 3.2.15 on 2022-10-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220920_1536'),
    ]

    operations = [
    ]
