# Generated by Django 3.2.15 on 2022-10-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221005_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribtion',
            options={'ordering': ['-id'], 'verbose_name': 'Подписка'},
        ),
    ]
