# Generated by Django 3.2.15 on 2022-10-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_subscribtion_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="subscribtion",
            options={
                "ordering": ["-id"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
